/**
 * DocumentsTracking Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportDocumentsTrackingExcel,
  exportStyledExcelWorkbook as exportDocumentsTrackingExcelWorkbook,
  exportStyledExcelTable as exportDocumentsTrackingExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as DocumentsTrackingExcelExportOptions,
  type StyledExcelSheet as DocumentsTrackingExcelSheet,
} from '@/app/Components/Export/ExcelExport';
