/**
 * DebitInsights Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportDebitInsightsExcel,
  exportStyledExcelWorkbook as exportDebitInsightsExcelWorkbook,
  exportStyledExcelTable as exportDebitInsightsExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as DebitInsightsExcelExportOptions,
  type StyledExcelSheet as DebitInsightsExcelSheet,
} from '@/app/Components/Export/ExcelExport';
