/**
 * CustomersSummaries Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportCustomersSummariesExcel,
  exportStyledExcelWorkbook as exportCustomersSummariesExcelWorkbook,
  exportStyledExcelTable as exportCustomersSummariesExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as CustomersSummariesExcelExportOptions,
  type StyledExcelSheet as CustomersSummariesExcelSheet,
} from '@/app/Components/Export/ExcelExport';
