/**
 * Emails Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportEmailsExcel,
  exportStyledExcelWorkbook as exportEmailsExcelWorkbook,
  exportStyledExcelTable as exportEmailsExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as EmailsExcelExportOptions,
  type StyledExcelSheet as EmailsExcelSheet,
} from '@/app/Components/Export/ExcelExport';
