/**
 * AdminControl Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportAdminControlExcel,
  exportStyledExcelWorkbook as exportAdminControlExcelWorkbook,
  exportStyledExcelTable as exportAdminControlExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as AdminControlExcelExportOptions,
  type StyledExcelSheet as AdminControlExcelSheet,
} from '@/app/Components/Export/ExcelExport';
