/**
 * CustomersDiscounts Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportCustomersDiscountsExcel,
  exportStyledExcelWorkbook as exportCustomersDiscountsExcelWorkbook,
  exportStyledExcelTable as exportCustomersDiscountsExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as CustomersDiscountsExcelExportOptions,
  type StyledExcelSheet as CustomersDiscountsExcelSheet,
} from '@/app/Components/Export/ExcelExport';

// Module-specific Excel exports
export * from '../ExportExcel';
