-- Run in Supabase SQL Editor
ALTER TABLE "bhs_CUSTOMERS"
ADD COLUMN IF NOT EXISTS "CUSTOMER CLASS" text;

UPDATE "bhs_CUSTOMERS"
SET "CUSTOMER CLASS" = 'B-CLASS'
WHERE "CUSTOMER CLASS" IS NULL OR TRIM("CUSTOMER CLASS") = '';
