/**
 * DataBase Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

import {
  exportStyledExcel as baseExportStyledExcel,
  exportStyledExcelWorkbook as baseExportStyledExcelWorkbook,
  exportStyledExcelTable as baseExportStyledExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions,
  type StyledExcelSheet,
} from '@/app/Components/Export/ExcelExport';

const DEFAULT_OPTIONS: StyledExcelExportOptions = {
  columnWidth: 14, // ~100 pixels (Excel uses character width, 1 char ≈ 7 pixels)
};

export async function exportDatabaseExcel(
  data: Record<string, unknown>[],
  fileName: string,
  options: StyledExcelExportOptions = {}
): Promise<void> {
  const cleanData = data.map(row => {
    const { ID, ...rest } = row;
    return rest;
  });
  return baseExportStyledExcel(cleanData, fileName, { ...DEFAULT_OPTIONS, ...options });
}

export async function exportDatabaseExcelWorkbook(
  sheets: StyledExcelSheet[],
  fileName: string
): Promise<void> {
  const styledSheets = sheets.map(sheet => {
    const cleanData = sheet.data.map(row => {
      const { ID, ...rest } = row;
      return rest;
    });
    return {
      ...sheet,
      data: cleanData,
      options: { ...DEFAULT_OPTIONS, ...sheet.options }
    };
  });
  return baseExportStyledExcelWorkbook(styledSheets, fileName);
}

export async function exportDatabaseExcelTable(
  headers: string[],
  rows: unknown[][],
  fileName: string,
  options: StyledExcelExportOptions = {}
): Promise<void> {
  return baseExportStyledExcelTable(headers, rows, fileName, { ...DEFAULT_OPTIONS, ...options });
}

export { recordsFromTable, type StyledExcelExportOptions, type StyledExcelSheet };
