/**
 * InventoryScrap Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportInventoryScrapExcel,
  exportStyledExcelWorkbook as exportInventoryScrapExcelWorkbook,
  exportStyledExcelTable as exportInventoryScrapExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as InventoryScrapExcelExportOptions,
  type StyledExcelSheet as InventoryScrapExcelSheet,
} from '@/app/Components/Export/ExcelExport';
