/**
 * CustomersDocuments Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportCustomersDocumentsExcel,
  exportStyledExcelWorkbook as exportCustomersDocumentsExcelWorkbook,
  exportStyledExcelTable as exportCustomersDocumentsExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as CustomersDocumentsExcelExportOptions,
  type StyledExcelSheet as CustomersDocumentsExcelSheet,
} from '@/app/Components/Export/ExcelExport';
