/**
 * Sales Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportSalesExcel,
  exportStyledExcelWorkbook as exportSalesExcelWorkbook,
  exportStyledExcelTable as exportSalesExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as SalesExcelExportOptions,
  type StyledExcelSheet as SalesExcelSheet,
} from '@/app/Components/Export/ExcelExport';
