/**
 * InventoryAnalysis Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportInventoryAnalysisExcel,
  exportStyledExcelWorkbook as exportInventoryAnalysisExcelWorkbook,
  exportStyledExcelTable as exportInventoryAnalysisExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as InventoryAnalysisExcelExportOptions,
  type StyledExcelSheet as InventoryAnalysisExcelSheet,
} from '@/app/Components/Export/ExcelExport';

// Module-specific Excel exports
export * from '../CategoriesAnalysis/ExcelExport';
