/**
 * CashReceipt Excel export entry point.
 * Generated by scripts/setup-module-excel-exports.mjs
 * Add module-specific formatting and export helpers here.
 */

export {
  exportStyledExcel as exportCashReceiptExcel,
  exportStyledExcelWorkbook as exportCashReceiptExcelWorkbook,
  exportStyledExcelTable as exportCashReceiptExcelTable,
  recordsFromTable,
  type StyledExcelExportOptions as CashReceiptExcelExportOptions,
  type StyledExcelSheet as CashReceiptExcelSheet,
} from '@/app/Components/Export/ExcelExport';
